name = "cslib"
version = "0.1.0"
defaultTargets = ["Cslib"]
testDriver = "CslibTests"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.21.0-rc3"

[[lean_lib]]
name = "Cslib"
globs = "Cslib.*"

[[lean_lib]]
name = "CslibTests"
globs = "CslibTests.+"
